obj-$(CONFIG_VIDEO_MEDIATEK_VCODEC) +=  vdec_vp8_if.o vdec_vp8_vpu.o

ccflags-y += \
    -I$(srctree)/drivers/media/platform/mtk-vcodec \
    -I$(srctree)/drivers/media/platform/mtk-vcodec/vp8_dec \
    -I$(srctree)/drivers/media/platform/mtk-vpu
