obj-$(CONFIG_VIDEO_MEDIATEK_MDP) += \
    mtk_mdp_core.o \
    mtk_mdp_m2m.o \
    mtk_mdp_regs.o \
    mtk_mdp_vpu.o

ccflags-y += \
    -I$(srctree)/drivers \
    -I$(srctree)/include \
    -I$(srctree)/drivers/media/platform/mtk-vcodec \
    -I$(srctree)/drivers/media/platform/mtk-vpu
