#
# Rockchip Clock specific Makefile
#

obj-y	+= clk-rockchip.o
obj-y	+= clk.o
obj-y	+= clk-pll.o
obj-y	+= clk-cpu.o
obj-y	+= clk-inverter.o
obj-y	+= clk-mmc-phase.o
obj-y	+= clk-muxgrf.o
obj-y	+= clk-ddr.o
obj-$(CONFIG_RESET_CONTROLLER)	+= softrst.o

obj-$(CONFIG_COMMON_CLK_RV1108)	+= clk-rv1108.o
obj-$(CONFIG_COMMON_CLK_RK3036)	+= clk-rk3036.o
obj-$(CONFIG_COMMON_CLK_RK3188)	+= clk-rk3188.o
obj-$(CONFIG_COMMON_CLK_RK3228)	+= clk-rk3228.o
obj-$(CONFIG_COMMON_CLK_RK3288)	+= clk-rk3288.o
obj-$(CONFIG_COMMON_CLK_RK3328)	+= clk-rk3328.o
obj-$(CONFIG_COMMON_CLK_RK3368)	+= clk-rk3368.o
obj-$(CONFIG_COMMON_CLK_RK3399)	+= clk-rk3399.o
