obj-$(CONFIG_VIDEO_MEDIATEK_VCODEC)+= \
    vdec_vp9_core.o \
    vdec_vp9_if.o \
    vdec_vp9_debug.o \
    vdec_vp9_vpu.o

ccflags-y += \
    -I$(srctree)/drivers/media/platform/mtk-vcodec \
    -I$(srctree)/drivers/media/platform/mtk-vcodec/vp9_dec \
    -I$(srctree)/drivers/media/platform/mtk-vpu
