/* Copyright Statement:
 * This firmware are protected under relevant copyright laws,
 * this information contained
 * herein is confidential and proprietary to Goodix.
 *
 * GOODIX (C) 2014-2016. All rights reserved.
 * Copyright (c) 2014-2016, The Linux Foundation. All rights reserved.
 *
 * WARNING:The GTP_COMPATIBLE_MODE part of this file
 * was generated by the specialized tools,
 * please do not modify it manually!
 *
 */

#ifndef _GT9XX_FIRMWARE_H_
#define _GT9XX_FIRMWARE_H_

#if GTP_HEADER_FW_UPDATE
unsigned char gtp_default_FW[] = {
	/* TODO:Puts your update firmware data here! */
};
#endif

#if GTP_COMPATIBLE_MODE
unsigned char gtp_default_FW_fl[] = {
};
#endif
#endif
